language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson libcanberra-gtk3-dev libllvm7 libgl1-mesa-dri libglx-mesa0 libglx0 libgl1 libgranite-dev libglvnd-dev libegl1-mesa-dev libgtk-3-dev libswitchboard-2.0-dev libpulse-dev valac"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja"

script:
 - echo BUILDS PASSED
